# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'Test'
    appSlug: 'mgerum-jnesis/Test-android-azure-devops'
    appFile: 'app/build/outputs/apk/debug/app-debug.apk'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: '123'
    destinationType: 'groups'
